// extras: use photos instead of colors for memory game, cool background, click event for card flips; click event that starts and restarts game; difficulty levels
const gameBoard = document.getElementById('game');
const gameCards = () => [
    {imgSrc: "./fotos/aLessonInRomantics.jpeg", name: 'A Lesson In Romantics'},
    {imgSrc: "./fotos/am.jpeg", name: "AM"},
    {imgSrc: "./fotos/aTodaCubaLeGusta.jpg", name: "A Toda Cuba Le Gusta"},
    {imgSrc: "./fotos/besitosYBesitas.jpeg", name: "Besitos Y Besitas"},
    {imgSrc: "./fotos/birthdays.jpeg", name: "Birthdays"},
    {imgSrc: "./fotos/blackPumas.jpeg", name: "Black Pumas"},
    {imgSrc: "./fotos/blkswn.jpeg", name: "blkswn"},
    {imgSrc: "./fotos/calambre.jpeg", name: "Calambre"},
    {imgSrc: "./fotos/caressYourSoul.png", name: "Caress Your Soul"},
    {imgSrc: "./fotos/collideWithTheSky.jpeg", name: "Collide With The Sky"},
    {imgSrc: "./fotos/comingHome.jpg", name: "Coming Home"},
    {imgSrc: "./fotos/cortasVenas.jpg", name: "Cortas Venas"},
    {imgSrc: "./fotos/cryBaby.png", name: "CryBaby"},
    {imgSrc: "./fotos/dejaEntendu.jpeg", name: "Deja Entendu"},
    {imgSrc: "./fotos/dejenmeLlorar.jpg", name: "Dejenme Llorar"},
    {imgSrc: "./fotos/gore.jpeg", name: "Gore"},
    {imgSrc: "./fotos/halfTheCity.jpeg", name: "Half the City"},
    {imgSrc: "./fotos/here.png", name: "Here"},
    {imgSrc: "./fotos/hozier.png", name: "Hozier"},
    {imgSrc: "./fotos/iDontLikeShit.jpeg", name: "I Don't Like Shit, I don't Go Outside"},
    {imgSrc: "./fotos/ifYoureReadingThisItsTooLate.png", name: "If You're Reading This It's Too Late"},
    {imgSrc: "./fotos/jardin.jpeg", name: "Jardin"},
    {imgSrc: "./fotos/KG0516.png", name: "KG0516"},
    {imgSrc: "./fotos/notesFromTheUnderground.jpeg", name: "Notes from the Underground"},
    {imgSrc: "./fotos/oasis.png", name: "Oasis"},
    {imgSrc: "./fotos/planetHer.png", name: "Planet Her"},
    {imgSrc: "./fotos/pony.jpeg", name: "Pony"},
    {imgSrc: "./fotos/positions.png", name: "Positions"},
    {imgSrc: "./fotos/sol.jpeg", name: "Sol"},
    {imgSrc: "./fotos/somethingToFeel.jpeg", name: "Something to Feel"},
    {imgSrc: "./fotos/somewhereAtTheBotomOfTheRiver.jpeg", name: "Somewhere at the Bottom of the River Between Vega and Altair"},
    {imgSrc: "./fotos/songsForImaginativePeople.jpeg", name: "Songs for Imaginative People"},
    {imgSrc: "./fotos/suga.jpeg", name: "SUGA"},
    {imgSrc: "./fotos/sway.jpg", name: "Sway"},
    {imgSrc: "./fotos/thaCarterIV.jpeg", name: "Tha Carter IV"},
    {imgSrc: "./fotos/theAvantGarden.jpeg", name: "The Avant Garden"},
    {imgSrc: "./fotos/theDutchess.png", name: "The Dutchess"},
    {imgSrc: "./fotos/theEmancipationOfMimi.jpg", name: "The Emancipation of Mimi"},
    {imgSrc: "./fotos/theHarderTheyFall.jpeg", name: "The Harder They Fall (Soundtrack)"},
    {imgSrc: "./fotos/theLastDonII.jpeg", name: "The Last Don II"},
    {imgSrc: "./fotos/theLumineers.jpeg", name: "The Lumineers"},
    {imgSrc: "./fotos/thePointOfItAll.jpg", name: "The Point of It All"},
    {imgSrc: "./fotos/tuVenenoMortal.jpg", name: "Tu Veneno Mortal"},
    {imgSrc: "./fotos/unpredictable.jpeg", name: "Unpredictable"},
    {imgSrc: "./fotos/unVeranoSinTi.jpeg", name: "Un Verano Sin Ti"},
    {imgSrc: "./fotos/venus.jpeg", name: "Venus"},
    {imgSrc: "./fotos/wastelandBaby.jpg", name: "Wasteland, Baby"},
    {imgSrc: "./fotos/xx.png", name: "XX"},
    {imgSrc: "./fotos/YHLQMDLG.png", name: "YHLQMDLG"},
    {imgSrc: "./fotos/zaba.jpeg", name: "Zaba"}
]